### ISSUE TITLE
No face found or face orientation not suitable for calculating FWHR

### ISSUE THREAD

**Issue by hobbes69** [TiesdeKok/fWHR_calculator#3]
"No face found or face orientation not suitable for calculating FWHR.

If this error pops up for all pictures, feel free to open an issue on the GitHub page so that I can look into it."

this error is coming up again - it was apparently resolved in January but the problem is back. Thanks!

**Comment by TiesdeKok** [comment]
@hobbes69 thanks for letting me know, I did notice that it has been going down more often than usual. Once I find some time I will look into this to see if I can resolve the problem!

**Comment by Mosquitozzz** [comment]
At 1st, thank you for the calculator and related info.

2. Calculator was working great, but for a long time (months) is not working, same issue as mention above. Is not recognizing excellent for fwhr analysis pictures/images, as any other pictures.

If you could be so kind, plz fix.

**Comment by ABABABO** [comment]
Can confirm, I have the same error as above too.

**Comment by TiesdeKok** [comment]
Thanks for the messages everyone. After going through the logs I suspect that it kept crashing due to excessive use. I could have programmed in a bunch of safeguards against this but instead I reprogrammed the calculations from the ground up with Javascript instead of relying on a Python API. This was initially not feasible but with recent advancements (in particular: https://github.com/justadudewhohacks/face-api.js) this became possible. Using this approach the calculations happen in the clients' browser making it substantially easier to scale. 

You can try the newest version here: https://www.tiesdekok.com/calculatefwhr/

I also added image upload and webcam support while I was at it.

**Comment by Mosquitozzz** [comment]
Thanks for looking into it, but new calculator is less ..correct. It often make wrong wide (bizygomatic) borders and also go little lower or little above then upper lip.
Also i have found u have changed upper border of fwhr based on upper lids to upper border of eyebrows. Why did u do that?
What is more correct? What is average fwhr standard based on upper lids border and based on eybrows border? Also in different literature it is or upper lids, or eybrows, but eybrowes again different - it is or in middle part of them or upper border of them. What is more correct? Where (in which scientific literature) it is written? 
...

**Comment by TiesdeKok** [comment]
The web-app has always been a toy-implementation for people that just want to try and get a quick estimate. 

If you care about accuracy then I recommend you to make your own implementation using Python, I have provided a pretty decent example. 

Feel free to contribute to this repository yourself if you feel like helping.

**Comment by Mosquitozzz** [comment]
I am just writing, that previous calculator was better and more accurate. It was good, only problem was it was crashing often.
A lot of people will be doing important wrong decisions basing on your new wrong fwhring calculator, do u understand that?
Previous 1 was much better. Just was crashing...

**Comment by Mosquitozzz** [comment]
Could u plz just give us back previous calculator, but working? New 1 is wrong fwhring. Very not good.
